services:
  mysql:
    image: mysql:8.3
    container_name: ec2-user-mysql-1
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: maquinasmedellin
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    container_name: ec2-user-web-1
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: maquinasmedellin
    restart: always

flyway:
  image: flyway/flyway:10
  depends_on:
    mysql:
      condition: service_healthy
  command: migrate
  environment:
    FLYWAY_URL: jdbc:mysql://mysql:3306/maquinasmedellin
    FLYWAY_USER: myuser
    FLYWAY_PASSWORD: mypassword
    FLYWAY_LOCATIONS: filesystem:/flyway/sql
  volumes:
    - ./db/migration:/flyway/sql


volumes:
  mysql_data:
